package it.szyszka.utils.server;

/**
 * Created by rafal on 19.09.17.
 */
public enum Response {

    NO_RESPONSE,
    USER_SAVED, EMAIL_TAKEN, NICKNAME_TAKEN,
    FAILED_TO_CREATE_TRUST_RELATION, SUCCESSFULLY_CREATED_TRUST_RELATION, FAILED_TO_CREATE_FRIEND_RELATION, SUCCESSFULLY_CREATED_FRIEND_RELATION,
    USER_ACCOUNT_ACTIVATED, DOWNLOADED_USER_FRIENDS, FAILD_TO_DOWNLOAD_USER_FRIENDS, TOKEN_NOT_FOUND

}
